// <auto-generated />
using FruityViceBestwayApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FruityViceBestwayApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240811123216_ChangedRelationships")]
    partial class ChangedRelationships
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FruityViceBestwayApp.Models.Entities.Fruit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fruits");
                });

            modelBuilder.Entity("FruityViceBestwayApp.Models.Entities.Nutrition", b =>
                {
                    b.Property<int>("FruitId")
                        .HasColumnType("int");

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double>("Sugar")
                        .HasColumnType("float");

                    b.HasKey("FruitId");

                    b.ToTable("Nutritions");
                });

            modelBuilder.Entity("FruityViceBestwayApp.Models.Entities.Nutrition", b =>
                {
                    b.HasOne("FruityViceBestwayApp.Models.Entities.Fruit", "Fruit")
                        .WithOne("Nutrition")
                        .HasForeignKey("FruityViceBestwayApp.Models.Entities.Nutrition", "FruitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fruit");
                });

            modelBuilder.Entity("FruityViceBestwayApp.Models.Entities.Fruit", b =>
                {
                    b.Navigation("Nutrition")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
